---

TestItems:
  Default:
    if-mode-access:
      type: "config"
      match: ["interface GigabitEthernet1/0/1","switchport mode (access)"]
      expected: access
    if-uplinks-shutdown:
      type: "config"
      match: ["interface GigabitEthernet1/1/[0-9]+","(shutdown)"]
      expected: shutdown
    if-unused-shutdown:
      type: "config"
      match: ["interface GigabitEthernet1/0/28+","(shutdown)"]
      expected: shutdown
    bin-test:
      cmd: "get info"
      match: "version ([0-9\\.]+).*"
      expected: "12.2"
    ip-test:
      cmd: "ip ssh version"
      match: "ip ssh version ([0-9])"
      expected: "2"
    domain:
      cmd: "config"
      match: "ip domain-name (.*)"
      expected: "net.local"


    NAS-unused-shutdown:
      type: "config"
      match: ["interface GigabitEthernet[0-9]/1/[1-4]","(shutdown)"]
      expected: shutdown
    NAS-int-desc-desk:
      type: "config"
      match: ["interface GigabitEthernet1/0/[1-8]","description (.*)"]
      expected: DESK
    NAS-int-access-desk:
      type: "config"
      match: ["interface GigabitEthernet1/0/8","switchport mode (.*)"]
      expected: access
    NAS-bin-test:
      cmd: "config"
      match: "version ([0-9\\.]+).*"
      expected: "15.2"
    NRT-bin-test:
      cmd: "config"
      match: "boot system flash bootflash:(isr4400-universalk9.03.16.02.S.155-3.S2-ext.SPA.bin)"
      expected: "isr4400-universalk9.03.16.02.S.155-3.S2-ext.SPA.bin"
    NRT-config-reg:
      cmd: "config"
      match: "config-register (0x2102)"
      expected: "0x2102"
      

    Air-Radius-1:
      cmd: "config"
      match: "version ([0-9\\.]+).*"
      expected: "15.2"
    Air-Radius-2:
      cmd: "config"
      match: "version ([0-9\\.]+).*"
      expected: "15.2"
    Air-domain:
      cmd: "config"
      match: "ip domain-name (airgc.net)"
      expected: "airgc.net"
    Air-ISE:
      type: "config"
      match: ["aaa group server radius AIRBNB-ISE","server name (radius-ise.airgc.net)"]
      expected: radius-ise.airgc.net
    Air-Admin:
      type: "config"
      match: ["aaa group server radius AIRBNB-NETADMINS","server name (asf1-saaa01-it)"]
      expected: asf1-saaa01-it
    Air-user-rescueadmin:
      cmd: "config"
      match: "username (rescueadmin) privilege 15 secret "
      expected: "rescueadmin"






    Test_217:
      match: "(line vty 0 4)"
      expected: "line vty 0 15"
    Test_218:
      match: "(access-class ACL_VTY_GNS in)"
      expected: "access-class ACL_VTY_GNS in"
    Test_219:
      match: "(exec-timeout 30 0)"
      expected: "exec-timeout 30"
    Test_220:
      match: "(transport input ssh)"
      expected: "transport input ssh"
    Test_221:
      match: "(line vty 5 15)"
      expected: "login local"
    Test_222:
      match: "(ntp source Loopback0)"
      expected: "ntp source Loopback0"
    Test_223:
      match: "(ntp server 10.252.194.22)"
      expected: "ntp server 10.252.194.22"
    Test_224:
      match: "(ntp server 10.136.193.22)"
      expected: "ntp server 10.136.193.22"
    Test_225:
      match: "(ntp server 10.252.194.23)"
      expected: "ntp server 10.252.194.23"
    Test_226:
      match: "(ntp server 10.136.193.23)"
      expected: "ntp server 10.136.193.23"
    Test_227:
      match: "(wsma agent exec)"
      expected: "no wsma agent exec"
    Test_228:
      match: "(wsma agent config)"
      expected: "no wsma agent config"
    Test_229:
      match: "(wsma agent filesys)"
      expected: "no wsma agent filesys"
    Test_230:
      match: "(wsma agent notify)"
      expected: "no wsma agent notify"
    Test_231:
      match: "(wsma profile listener httplistener)"
      expected: "no wsma profile listener httplistener"
    Test_232:
      match: "(wsma profile listener httpslistener)"
      expected: "no wsma profile listener httpslistener"
    Test_233:
      match: "(ap group default-group)"
      expected: "no ap group default-group"
  'Catalyst3750':
    bin-test:
      cmd: "show info"
      match: "version (12).*"
      expected: "12"
  'NASDevice':
    NAS-bin-test:
      cmd: "get info"
      match: "version ([0-9\\.]+).*"
      expected: "15.2"

TestGroups:
  NASTest:
    - NAS-bin-test
    - NAS-unused-shutdown
    - NAS-int-desc-desk
    - NAS-int-access-desk
    - Air-domain
    - Air-ISE
    - Air-Admin
    - Air-user-rescueadmin
  NRTTest:
    - Air-user-rescueadmin
    - NRT-bin-test
    - NRT-config-reg
  NewBasicTest:
    - if-mode-access
    - if-uplinks-shutdown
    - if-unused-shutdown
    - bin-test
    - domain


  Basic:
    - ip-test
    - bin-test
    - domain
    - Test_5
    - Test_6
    - Test_7
    - Test_8
    - Test_11
    - Test_12
    - Test_13
    - Test_17
    - Test_18
    - Test_22
    - Test_23
    - Test_24
    - Test_25
    - Test_26
    - Test_27
    - Test_28
    - Test_29
    - Test_30
    - Test_31
    - Test_32
    - Test_33
    - Test_34
    - Test_35
    - Test_41
    - Test_47
    - Test_53
    - Test_54
    - Test_55
    - Test_59
    - Test_60
    - Test_61
    - Test_62
    - Test_63
    - Test_64
    - Test_65
    - Test_66
    - Test_69
    - Test_70
    - Test_71
    - Test_72
    - Test_73
    - Test_74
    - Test_75
    - Test_79
    - Test_80
    - Test_81
    - Test_82
    - Test_83
    - Test_85
    - Test_86
    - Test_87
    - Test_88
    - Test_89
    - Test_90
    - Test_91
    - Test_92
    - Test_93
    - Test_95
    - Test_96
    - Test_98
    - Test_99
    - Test_101
    - Test_102
    - Test_105
    - Test_107
    - Test_108
    - Test_109
    - Test_110
    - Test_112
    - Test_113
    - Test_114
    - Test_118
    - Test_120
    - Test_121
    - Test_122
    - Test_123
    - Test_125
    - Test_126
    - Test_130
    - Test_131
    - Test_132
    - Test_133
    - Test_134
    - Test_135
    - Test_137
    - Test_138
    - Test_139
    - Test_140
    - Test_141
    - Test_143
    - Test_144
    - Test_145
    - Test_146
    - Test_148
    - Test_150
    - Test_151
    - Test_152
    - Test_154
    - Test_155
    - Test_157
    - Test_158
    - Test_164
    - Test_165
    - Test_166
    - Test_167
    - Test_168
    - Test_169
    - Test_170
    - Test_171
    - Test_172
    - Test_173
    - Test_174
    - Test_175
    - Test_176
    - Test_177
    - Test_178
    - Test_179
    - Test_180
    - Test_181
    - Test_182
    - Test_183
    - Test_184
    - Test_185
    - Test_186
    - Test_187
    - Test_188
    - Test_189
    - Test_190
    - Test_191
    - Test_192
    - Test_194
    - Test_195
    - Test_196
    - Test_197
    - Test_198
    - Test_199
    - Test_201
    - Test_203
    - Test_204
    - Test_205
    - Test_206
    - Test_207
    - Test_208
    - Test_209
    - Test_210
    - Test_211
    - Test_212
    - Test_213
    - Test_214
    - Test_215
    - Test_216
    - Test_217
    - Test_218
    - Test_219
    - Test_220
    - Test_221
    - Test_222
    - Test_223
    - Test_224
    - Test_225
    - Test_226
    - Test_227
    - Test_228
    - Test_229
    - Test_230
    - Test_231
    - Test_232
    - Test_233





